"William C. Dawn
" wdawn730@gmail.com
" Created December 2018
" Last Modified April 2020

" do not use vi keybindings
set nocompatible
" but also dont wait for me to press an arrow key
set ttimeoutlen=50

" disable all bold
set t_md=
" i like peachpuff...
colorscheme peachpuff
syntax enable

" save the viminfo file in a more hidden place
" viminfo is in the .gitignore file so all should be well
set viminfo+=n~/.vim/viminfo

" set colors and format for statusline (line at bottom)
hi User1 ctermbg=9 cterm=reverse,bold
hi User2 ctermbg=21 cterm=reverse,bold
" statusline is always on
set laststatus=2
set statusline=
set statusline+=\ %f\ %1*%m%0*
" switching to right side
set statusline+=%=
set statusline+=%2*\ %-12y%0*
set statusline+=L\:%4l\/%-5L\ \ C%-3c\ %-10P

" set highlighting for searching
set hlsearch
set incsearch

" set default tab properties
set tabstop=2
set shiftwidth=2
set softtabstop=2
" spaces are better than tabs
set expandtab   
set autoindent

" some tab properties are file depdent
" for filetype specific data, see ~/.vim/after/ftplugin/*.vim
filetype plugin indent on

" 80 character line length and text wrapping
set textwidth=80
set colorcolumn=+1 

" format options
"   t = autowrap using text width
"   c = auto-wrap comments using textwidth
"   a = automatic formatting of paragraphs
"set formatoptions=tca

" by default do not wrap lines that run longer than the terminal
set nowrap

" set hybrid line numbering
set number
set relativenumber

" map key for spell cheking
map <F7> :set spell spelllang=en_us<CR>
map <F8> :set nospell<CR>

" easier split navigation (save a kepress)
noremap <C-J> <C-W><C-J>
noremap <C-K> <C-W><C-K>
noremap <C-L> <C-W><C-L>
noremap <C-H> <C-W><C-H>
" more natural split opening
set splitbelow
set splitright

" disable all beeps
set vb t_vg=

" always open *.tex files using LaTeX highlighting
let g:tex_flavor='latex'

" these are bizarre variables to specify fotran formatting
" they must be here as well for new files with fortran exensions
" allow free source not character based
let fortran_free_source=1
" indent between do & enddo
let fortran_do_enddo=1

" plugins
" run :PlugInstall
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')

Plug 'junegunn/goyo.vim'
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

" important to reduce update time for gitgutter
set updatetime=100

" fix colors for gitgutter
"let g:gitgutter_override_sign_column_highlight = 0
highlight clear SignColumn
highlight GitGutterAdd ctermfg=2
highlight GitGutterChange ctermfg=3
highlight GitGutterDelete ctermfg=1
highlight GitGutterChangeDelete ctermfg=4

" treat *.xmf files as xml
" these are used for visualiztion with xmf/hdf5 files
au BufReadPost *.xmf set syntax=xml

" generate vim spell binary as necessary
for d in glob('~/.vim/spell/*.add', 1, 1)
    if filereadable(d) && (!filereadable(d . '.spl') || getftime(d) > getftime(d . '.spl'))
        silent exec 'mkspell! ' . fnameescape(d)
    endif
endfor

" TODO
" * clang-format

" different cursors for normal and insert mode
" Ps = 0  -> blinking block.
" Ps = 1  -> blinking block (default).
" Ps = 2  -> steady block.
" Ps = 3  -> blinking underline.
" Ps = 4  -> steady underline.
" Ps = 5  -> blinking bar (xterm).
" Ps = 6  -> steady bar (xterm).
let &t_SI = "\e[6 q"
let &t_EI = "\e[4 q"

" sync clipboard with Vim
set clipboard=unnamedplus
