" William C. Dawn
" wdawn730@gmail.com
" December 2018 

" do not use vi keybindings
set nocompatible 
" but also dont wait for me to press an arrow key
set ttimeoutlen=50

" we need syntax highligting
syntax on

" save the viminfo file in a more hidden place
" viminfo is in the .gitignore file so all should be well
set viminfo+=n~/.vim/viminfo

" set color and appearance settings
colors desert

" set colors and format for statusline (line at bottom)
hi User1 ctermbg=9 cterm=reverse,bold
hi User2 ctermbg=21 cterm=reverse,bold
set laststatus=2 " statusline is always on
set statusline=
set statusline+=\ %f\ %1*%m%0*
" switching to right side
set statusline+=%=
set statusline+=%2*\ %-12y%0*\ 
set statusline+=L\:%4l\/%-5L\ \ C%-3c\ %-10P

" set highlighting for searching
set hlsearch
set incsearch

" set default tab properties
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab   " spaces are better than tabs
set autoindent

" some tab properties are file depdent
" for filetype specific data, see ~/.vim/after/ftplugin/*.vim
filetype plugin indent on
"
" 80 character line length and text wrapping
set textwidth=80
set colorcolumn=+1 

"
" format options
"   t = autowrap using text width
"   c = auto-wrap comments using textwidth
"   a = automatic formatting of paragraphs
"set formatoptions=tca
"

" by default do not wrap lines that run longer than the terminal
set nowrap

" set hybrid line numbering
set number
set relativenumber

" map key for spell cheking
map <F7> :set spell spelllang=en_us<CR>
map <F8> :set nospell<CR>

" easier split navigation (save a kepress)
noremap <C-J> <C-W><C-J>
noremap <C-K> <C-W><C-K>
noremap <C-L> <C-W><C-L>
noremap <C-H> <C-W><C-H>
" more natural split opening
set splitbelow
set splitright

" TODO
" * see if there is a nicer word wrap for LaTeX
" * trailing whitespace
" * Goyo plugin for simpler writing
