#! /bin/bash

# key bindings
pkill sxhkd &

DOCKED=2

# screen layout
case $DOCKED in
  0)
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    sxhkd &
  ;;
  1)
    $HOME/.config/bspwm/screenlayout.sh
    bspc monitor HDMI2 -d 1 3 5 7 9
    bspc monitor HDMI3 -d 2 4 6 8 10
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc_docked &
  ;;
  2)
    $HOME/.config/bspwm/screenlayout.sh
    bspc monitor DVI-I-1 -d 1 3 5 7 9
    bspc monitor DP-1 -d 2 4 6 8 10
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc_work &
  ;;
esac

# composition manager (transparency)
picom -bC & # run in background, no shadow on menus

# desktop background
feh --bg-scale $HOME/.config/i3/dune2.jpg &

# setup bar
pkill polybar 
$HOME/.config/polybar/launch_polybar.sh &

bspc config border_width         2
bspc config window_gap           7

# to work with spacing for polybar
bspc config top_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

# image magick pyton should be floating and centered
bspc rule -a Display state=floating
bspc config external_rules_command $HOME/.config/bspwm/float_image.sh

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
