#! /bin/bash

xrdb ~/.Xresources

# key bindings
pkill sxhkd

DESKTOP=3

################################################################################
# screen layout
################################################################################
case $DESKTOP in
  0)
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    sxhkd &
  ;;
  1)
    export MONITOR_L='HDMI2'
    export MONITOR_R='HDMI3'
    $HOME/.config/bspwm/screenlayout.sh
    bspc monitor $MONITOR_L -d 1 3 5 7 9
    bspc monitor $MONITOR_R -d 2 4 6 8 10
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc_docked &
  ;;
  2)
    export MONITOR_L='DVI-I-1'
    export MONITOR_R='DP-1'
    $HOME/.config/bspwm/screenlayout.sh
    bspc monitor $MONITOR_L -d 1 3 5 7 9
    bspc monitor $MONITOR_R -d 2 4 6 8 10
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc_docked &
  ;;
  3)
    export MONITOR_L='HDMI-0'
    export MONITOR_R='DP-3'
    $HOME/.config/bspwm/screenlayout.sh
    bspc monitor $MONITOR_L -d 1 3 5 7 9
    bspc monitor $MONITOR_R -d 2 4 6 8 10
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc_docked &
esac

# automatically focus on workspace 1
bspc desktop -f '^1'

# composition manager (transparency)
pkill picom
picom -bC & # run in background, no shadow on menus

# desktop background
pkill feh
# feh --bg-scale $HOME/.config/bspwm/dune2.jpg &
feh --bg-scale $HOME/.config/bspwm/going_to_the_sun.jpg &
# feh --bg-scale $HOME/.config/bspwm/grinnell_glacier.jpg &

# setup bar
pkill polybar
amixer set Master 0%
$HOME/.config/polybar/launch_polybar.sh &

# unclutter to hide cursor when not in use
pkill unclutter
unclutter &

################################################################################
xrdb ~/.Xresources
# load xresources to $color0 .. $color15
for x in "$(xrdb -query | grep color[0-9] | sed "s/^\*//g" | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

# bspc config
################################################################################

bspc config border_width  4
bspc config border_radius 12
bspc config window_gap    12

bspc config normal_border_color  $color0
bspc config active_border_color  $color0 # "active" is the last window used on a given workspace (monitor)
bspc config focused_border_color $color4
bspc config presel_border_color  $color12

# to work with spacing for polybar
bspc config top_padding 30

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

################################################################################
# bspc rule(s)
################################################################################
bspc rule -a Zathura state=tiled
# regenerate colors for zathura
$HOME/.config/zathura/zathura_colors.sh > $HOME/.config/zathura/zathurarc

# image magick python should be floating and centered
bspc rule -a Display state=floating
bspc config external_rules_command $HOME/.config/bspwm/float_image.sh

# matplotlib figures are floating
bspc rule -a Matplotlib state=floating

# browser is on 10
bspc rule -a $BROWSER desktop='^10' follow=on

# matplotlib figures are floating
bspc rule -a Matplotlib state=floating

# defaults shipped with bspwm
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
