#!/bin/bash

SLEEPTIME=2
degF='°F'
TWARN=140
CPUWARN=80

# get xresources colors
for x in "$(xrdb -query | grep color[0-9] | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done
# ! black
# *.color0:  *.color8:
# ! red
# *.color1:  *.color9:
# ! green
# *.color2:  *.color10
# ! yellow
# *.color3:  *.color11
# ! blue
# *.color4:  *.color12
# ! magenta
# *.color5:  *.color13
# ! cyan
# *.color6:  *.color14
# ! white
# *.color7:  *.color15

# assume lm-sensors
CPUTEMP=$(sensors -f | awk '/^Core 0:/ {printf "%.0f\n",$3}')

# /proc/stat keeps the total time dedicated to each process since boot!!!
# I need to subtract the difference between two times.
# $2=user
# $3=niced
# $4=system
# $5=idle
# $6=iowait
# $7=irq
# $8=softirq

IDOLD=$(grep 'cpu ' /proc/stat | awk '{printf "%d",$5}')
TOTALOLD=$(grep 'cpu ' /proc/stat | awk '{tot=($2+$3+$4+$5+$6+$7+$8)} END {printf "%d\n",tot}')

sleep $SLEEPTIME

IDNEW=$(grep 'cpu ' /proc/stat | awk '{printf "%d",$5}')
TOTALNEW=$(grep 'cpu ' /proc/stat | awk '{tot=($2+$3+$4+$5+$6+$7+$8)} END {printf "%d\n",tot}')

ID=$(awk -v a="${IDOLD}" -v b="${IDNEW}" -v c="${TOTALOLD}" -v d="${TOTALNEW}" 'BEGIN {printf "%.2f%\n", ((b-a)/(d-c))*100}')
USE=$(awk -v id="${ID}" 'BEGIN {printf "%.2f\n", (100-id)}')

WHITE='#FFFFFF'
if [ "$CPUTEMP" -gt "$TWARN" ]
then
  TEMPCOLOR=$color9
else
  TEMPCOLOR=$WHITE
fi

USEINT=$(printf "%.0f" $USE)
if [ "$USEINT" -gt "$CPUWARN" ]
then
  USECOLOR=$color11
else
  USECOLOR=$WHITE
fi

printf "<span color='%s'>%s%s</span> " $USECOLOR $USE "%"
printf "<span color='%s'>%s%s</span>" $TEMPCOLOR $CPUTEMP $degF
