#!/bin/bash

# used/free percentage to two decimal places
# do not use -h here or division gets screwy
PERCENT=$(free | awk '/^Mem:/ {printf "%.2f%\n",($3/$2*100)}')

# used/free in human text
USEDFREE=$(free -h | awk '/^Mem:/ {printf "%s/%s\n",$3,$2}')

printf "%7s %s\n"  $PERCENT $USEDFREE
