#!/bin/bash

# get xresources colors
for x in "$(xrdb -query | grep color[0-9] | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done
# ! black
# *.color0:  *.color8:
# ! red
# *.color1:  *.color9:
# ! green
# *.color2:  *.color10
# ! yellow
# *.color3:  *.color11
# ! blue
# *.color4:  *.color12
# ! magenta
# *.color5:  *.color13
# ! cyan
# *.color6:  *.color14
# ! white
# *.color7:  *.color15

FUL=$color2
MID=$color3
EMP=$color1


CAPACITY=$(cat /sys/class/power_supply/$1/capacity) || exit
STATUS=$(cat /sys/class/power_supply/$1/status)

if [ $CAPACITY -ge 67 ]
then
  COLOR=$FUL
elif [ $CAPACITY -ge 33 ]
then
  COLOR=$MID
else
  COLOR=$EMP
fi

if [ $STATUS = "Charging" ]
then
  COLOR=william
fi

printf "<span color='%s'>%s%s</span>" $COLOR $CAPACITY "%"
